CLASS zamb_holamundo_001 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zamb_holamundo_001 IMPLEMENTATION.


  METHOD IF_OO_ADT_CLASSRUN~main.
  out->write( 'hola mundo' ).
  ENDMETHOD.
ENDCLASS.
